version: '2'
services:
  apinf:
    image: apinf/platform
    restart: always
    env_file:
      - 'docker/env.apinf'
    environment:
      - MONGO_URL=mongodb://mongo/apinf_db
    depends_on:
      - mongo
      - ssl
    links:
      - elasticsearch:elasticsearch.docker
  apiumbrella:
    image: nrel/api-umbrella:0.13.0
    restart: always
    command: bash -c "apt-get update && apt-get install -qq -y --no-install-recommends curl && api-umbrella run"
    volumes:
      - ./docker/api-umbrella/config:/etc/api-umbrella
      - letsencrypt:/etc/letsencrypt
      - apiumbrella_db:/opt/api-umbrella/var/db
      - apiumbrella_log:/opt/api-umbrella/var/log
    ports:
      - "3001:3001"
      - "3002:3002"
    depends_on:
      - ssl
      - mongo
    links:
      - elasticsearch:elasticsearch.docker
  mongo:
    restart: always
    image: mongo:3.2.6
    command: --storageEngine wiredTiger
  ssl:
    restart: always
    image: smashwilson/lets-nginx
    env_file:
      - 'docker/env.ssl'
    environment:
      - UPSTREAM=apinf:3000
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - letsencrypt:/etc/letsencrypt
      - letsencrypt_backups:/var/lib/letsencrypt
      - dhparam_cache:/cache
  elasticsearch:
    image: elasticsearch:2.4
    restart: always
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
volumes:
    letsencrypt: {}
    letsencrypt_backups: {}
    dhparam_cache: {}
    elasticsearch_data: {}
    apiumbrella_db: {}
    apiumbrella_log: {}
